name: Android
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  buildInContainer:
    runs-on: ubuntu-latest
    container:
      image: docker://subsurface/android-build-container:5.13.12

    steps:
    - name: checkout sources
      uses: actions/checkout@v1

    - name: run build
      run: |
        cd ..
        ln -s /android/Qt .
        ln -s /android/android-ndk-r18b .
        ln -s /android/android-sdk-linux .
        ls -l
        bash -x subsurface/packaging/android/android-build-wrapper.sh
        cp /__w/subsurface/subsurface-mobile-build-arm64/*mobile*/build/outputs/apk/debug/subsurface-mobile-arm64-v8a-debug.apk ${GITHUB_WORKSPACE}/Subsurface-mobile.arm64.apk
        cp /__w/subsurface/subsurface-mobile-build-arm/*mobile*/build/outputs/apk/debug/subsurface-mobile-armeabi-v7a-debug.apk ${GITHUB_WORKSPACE}/Subsurface-mobile.apk

    - name: prepare PR artifacts
      if: github.event_name == 'pull_request'
      run: |
        mkdir -p Android-artifacts
        mv Subsurface-mobile.apk Subsurface-mobile.arm64.apk Android-artifacts

    - name: PR artifacts
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: Android-artifacts
        path: Android-artifacts
